### ISSUE TITLE
Problem with input vectors in function 'is_equiv_lattice'

### ISSUE THREAD

**Issue by t-reents** [msg-byu/enumlib#117]
Hi,

I am trying to use the code to create possible NCA structures based on a LiNiO2 input structure. The input file looks as follows:
```
LiNiO2
bulk
4.873497 -1.454063 0.000000
4.873497 1.454063 0.000000
4.439660 0.000000 2.480864
5
4
7.093327 0.000000 1.240432 4
0.000000 0.000000 0.000000 0/1/2
3.661235 0.000000 0.640251 3
10.525419 0.000000 1.840613 3
20 20
0.00001
full
3 3 80
3 3 80
14 14 80
40 40 80
20 20 80
```

When I execute the code using that input file, the program immediately fails with the following error message:
`STOP Problem with input vectors in function 'is_equiv_lattice'`

Thanks a lot in advance!

**Comment by glwhart** [comment]
I can reproduce this, but not sure why it is happening yet. I started debugging yesterday. Hope to have something soon. Sorry for the wait.

**Comment by t-reents** [comment]
No problem! Thank you for checking it.

**Comment by glwhart** [comment]
The error message `STOP Problem with input vectors in function 'is_equiv_lattice'` is a red-herring and i is probably coming about because of some overflow problem (your problem is combinatorially large). But one problem is apparent (sorry I didn't notice it sooner)---your stoichiometry requirements are not possible in the supercell you have chosen. You are enumerating supercells 20x bigger than the parent. So you have 20 sites that are allowed to take atoms of type 0/1/2. But then you require that only 3/80 of them have type 0 (same for type 1) but that is impossible since there are only 20 sites. Your requirement must be divisible by 20. Here's a combinatorially much smaller combinatorially that seems to run just fine:

```
LiNiO2
bulk
4.873497 -1.454063 0.000000
4.873497 1.454063 0.000000
4.439660 0.000000 2.480864
5
4
7.093327 0.000000 1.240432 4
0.000000 0.000000 0.000000 0/1/2
3.661235 0.000000 0.640251 3
10.525419 0.000000 1.840613 3
8 8
0.00001
full
0 1 8
0 1 8
1 2 8
4 4 8
2 2 8
```
and the output
```
➜  input git:(main) ✗ ../../src/enum.x
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n= 8 to  8
Including only structures of which the concentration of each atom is in the range:
Type: 1: 0/8--1/8
Type: 2: 0/8--1/8
Type: 3: 1/8--2/8
Type: 4: 4/8--4/8
Type: 5: 2/8--2/8
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
   8         0.1103      155     3        42        0.7290        4786        4786
---------------------------------------------------------------------------------------------
```

**Comment by glwhart** [comment]
A size 12 case runs in about 6 seconds on my laptop but still gives more than half a million structures:
```
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n=12 to 12
Including only structures of which the concentration of each atom is in the range:
Type: 1: 0/12--1/12
Type: 2: 0/12--1/12
Type: 3: 1/12--3/12
Type: 4: 6/12--6/12
Type: 5: 3/12--3/12
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
  12         6.0503      455     2       104        0.7714      677565      677565
---------------------------------------------------------------------------------------------
```

**Comment by glwhart** [comment]
>  But then you require that only 3/80 of them have type 0 (same for type 1) but that is impossible since there are only 20 sites.

What I said here, isn't quite right. Because the concentration refers to that of the entire cell, not just one site, 3/80 would mean that 3/20 of the 0/1/2 sites would be occupied by a 0. That should be possible. I started with a smaller cell (one that I know didn't have potential overflow problems) with stoichiometry close to your original input and I'm trying to "sneak up" on your target. Here's one for size 16:
```
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n=16 to 16
Including only structures of which the concentration of each atom is in the range:
Type: 1: 3/64--3/64
Type: 2: 3/64--3/64
Type: 3: 10/64--10/64
Type: 4: 8/16--8/16
Type: 5: 4/16--4/16
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
  16        13.0978      651     4       147        0.7742      639034      639034
---------------------------------------------------------------------------------------------
```

**Comment by t-reents** [comment]
Exactly, I was already trying to clarify the concentration ranges. As you said, in principle it should be possible.

**Comment by t-reents** [comment]
As expected the number of possible structures will be quite large, anyway. I need to clarify with my colleague whether we need the exact stochiometry or whether similar stochiometries would be fine, too. Certainly, it would be useful to stick to some smaller cells

**Comment by glwhart** [comment]
Jumping from my n=16 case to n=18, I already have overflow problems (before I even try 20). Note that in my 16 case, we already have 600K structures and enumerations tend to increase exponentially (like a factorial), so it might not be possible to go to n=20.

In any case, the error message is not helpful. I'll look at a way of improving the error handling.

**Comment by glwhart** [comment]
Here's some input for n=16 that gives a small range of concentrations around your original target. This enumeration gives about 2.3M structures.
```
LiNiO2
bulk
4.873497 -1.454063 0.000000
4.873497 1.454063 0.000000
4.439660 0.000000 2.480864
5
4
7.093327 0.000000 1.240432 4
0.000000 0.000000 0.000000 0/1/2
3.661235 0.000000 0.640251 3
10.525419 0.000000 1.840613 3
16 16
0.00001
full
1 4 64
1 4 64
10 14 64
8 8 16
4 4 16
```

**Comment by t-reents** [comment]
Makes totally sense. I just thought it would work, based on a previous enumeration task with a supercell containing also 80 atoms. But in that case, the parent cell was already much larger so that the number of enumerations was smaller. I have not considered this properly in the beginning. Thank you for your support

**Comment by glwhart** [comment]
I think it might still work. I'm not sure the problem is the number of configurations, but rather the number/size of the enumerated supercells. Rather than overflow, I'm starting to suspect a roundoff error. I'll dig into this today and see if it is fixable. In the meantime, maybe the size 16 can get you started.

**Comment by glwhart** [comment]
I made two very small changes, one in symlib and one in enumlib, relaxing the tolerance of the error checking in a small 3x3 matrix inverse. This makes it possible for your case to run, avoiding errors triggering when they shouldn't merely because of small round-off errors. 

I did a fresh checkout of enumlib, and symlib as a submodule, recompiled and ran your case from scratch:

```
➜  input git:(main) ✗ ../../src/enum.x   
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n=20 to 20
Including only structures of which the concentration of each atom is in the range:
Type: 1: 3/80--3/80
Type: 2: 3/80--3/80
Type: 3: 14/80--14/80
Type: 4: 40/80--40/80
Type: 5: 20/80--20/80
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
  20        29.0997     1085     2       220        0.7972     3969218     3969218
---------------------------------------------------------------------------------------------
```

**Comment by glwhart** [comment]
With the new changes, I got this one to run as well. Looks like size-wise, the code can go a lot larger now, as long as the number of configs doesn't explode (which is the case for enumerations with highly restricted concentration ranges).
```
➜  input git:(main) ✗ ../../src/enum.x
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n=24 to 24
Including only structures of which the concentration of each atom is in the range:
Type: 1: 3/96--3/96
Type: 2: 3/96--3/96
Type: 3: 18/96--18/96
Type: 4: 12/24--12/24
Type: 5: 6/24--6/24
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
  24       225.7475     2015     3       414        0.7945    20721433    20721433
---------------------------------------------------------------------------------------------
```
