### ISSUE TITLE
Conda package for enumlib

### ISSUE THREAD

**Issue by shyuep** [msg-byu/enumlib#27]
To make it easier for others to work with enumlib, I have created a conda build for OSX and Linux at the matsci channel on Anaconda cloud (https://anaconda.org/matsci). It is my hope that this will be a collection of useful software for materials science (e.g., enumlib, spglib, pymatgen, etc.). Users can then install these packages easily using `conda install --channel matsci enumlib` for example. 

I would like to request that perhaps these resources can perhaps be highlighted in the documentation somewhere for enumlib. Also, some versioning of enumlib would be helpful to end users. For the developers, the conda build script is available at https://github.com/materialsvirtuallab/materials.sh/tree/master/conda-skeletons/platform/enumlib. I have assigned an arbitrary version number of 1.0 for now.

**Comment by wsmorgan** [comment]
Hello,

As part of our next commit we are adding a note in our README the informs users of the option to compile using conda. We have versioning on enumlib which can be viewed in our HISTORY.md file for those who are interested.

You should know that as of revision 1.0.4 which will be released shortly the script you have constructed for compiling enumlib will no longer function since we have restructured the repository so that symlib is now a submodule and is cloned inside the enumlib folder. Additionally we are also adding a dependence on a new repository that allows the code to predict the number of unique arrangements without having to do a full enumeration. This repository is also a submodule that appears inside the enumlib folder. 

Let us know if you have any difficulties with the new structure.

**Comment by shyuep** [comment]
Thanks. I have updated the conda build recipe. Also, I linked the whole repo of materials.sh into a continuous integration service Travis CI. In this way, everything I increment a version number, a new set of enumlib (or any other package for that matter) will be built for all supported platforms (for enumlib, only Linux and OSX) and uploaded automatically onto the matsci channel on Anaconda Cloud. 

Using anaconda cloud means that typical users do not need to install gfortran (a problem on Mac, which does not come with it by default) or do any compilation to use these tools.

Thanks for the great package! We use it extensively in the materials project as well as in my group!
