### ISSUE TITLE
makestr.py is generating the wrong structure 

### ISSUE THREAD

**Issue by nycmouli** [msg-byu/enumlib#45]
In concentrated restricted enumeration, the makestr.py is creating the poscar file for the wrong structure. It's off by 3. 

ex: python makestr.py 15 
Generates poscar vasp.12

**Comment by wsmorgan** [comment]
The problem was that when concentrations are being restricted the code prints out the concentration restrictions to struct_enum.out. This offset the line count in the python scripts. The code has been fixed so that if the concentration check flag is True then the offset used to start counting the actual structures is adjusted by the number of elements present in the system.

**Comment by wsmorgan** [comment]
Fixed in revision 1.0.9.
