### ISSUE TITLE
Question about concentration constraint

### ISSUE THREAD

**Issue by feifzhou** [msg-byu/enumlib#52]
Hi Gus,

Hope all is well. Could you help me with my problem here? The cell is

Ba1 Si4 N4
bulk
-4.1280603611777718 4.1280603611777718 1.7254000000000000
4.1280603611777718 -4.1280603611777718 1.7254000000000000
4.1280603611777718 4.1280603611777718 -1.7254000000000000
4
5
   2.61719026898670   1.09806405607329   1.72540000000000  0/1 
  -1.09806405607329   2.61719026898670   1.72540000000000  0/1 
   1.51087009219107   3.02999630510448   0.00000000000000  0/1 
   5.22612441725106   1.51087009219107   0.00000000000000  0/1 
0.0000000000000000 0.0000000000000000 0.0000000000000000 2/3
1 1
1E-6
full
#
20 26 100 # VARY CONSTRAINT
0 100 100
0 100 100
0 100 100

So basically two sublattices, Mg/Si on the first 4 sites, Sr/Ba on the 5th site. I want a 1:3 ratio of Si:Mg on the first sublattice. But running with concentration constraint gives me some puzzling results. 

* If I put 25 25 100 on the # VARY CONSTRAINT line above, no output was generated. 

* If I put 20 25 100 on the # VARY CONSTRAINT line above, I got the expected enumerations. 

The problem seems to be related to the second sublattice. If I remove it from the problem:

Ba1 Si4 N4
bulk
-4.1280603611777718 4.1280603611777718 1.7254000000000000
4.1280603611777718 -4.1280603611777718 1.7254000000000000
4.1280603611777718 4.1280603611777718 -1.7254000000000000
2
4
   2.61719026898670   1.09806405607329   1.72540000000000  0/1 
  -1.09806405607329   2.61719026898670   1.72540000000000  0/1 
   1.51087009219107   3.02999630510448   0.00000000000000  0/1 
   5.22612441725106   1.51087009219107   0.00000000000000  0/1 
1 1
1E-6
full
#
25 25 100
0 100 100

Then "25 25 100" works properly.

Best regards,
Fei

**Comment by feifzhou** [comment]
Sorry the comment line in struct_enum.in was formatted by the system as a horizontal line. But you know what I mean.

**Comment by glwhart** [comment]
If you don't have a line for each site, specifying the concentrations, then all concentrations are tried. That's a HUGE space to work in (quaternary). The code probably is working but just running a long time. When you take out the 5th atom, you get a binary. Much, much smaller problem. Code runs.

I'm guessing the problem is binary(small) vs quaternary (big). Which version are you using? We updated the algorithm to be more efficient on these restricted concentration, high-k searches...

**Comment by wsmorgan** [comment]
If I understand right the code is running to completion and producing no output right? It looks like you have 5 atoms in the basis and you aren't making supercells, i.e., cells with larger volumes. If I'm reading all that right then you can't have a cell in which 25% of the atoms are of species `0` the least you can have is 20% and the next option is 40%. When you specify 25 25 100 the code returns nothing because there are no possible arrangements in which a 25% mix of the first species can be found.

**Comment by glwhart** [comment]
I think Wiley's observation is correct. When I responded I missed the fact that you weren't going any bigger than a single cell...

**Comment by feifzhou** [comment]
My cell has two sublattices:
* sublattice 1 with 4 sites in the primitive cell and atomic species A, B,
for which I'd like to fix the A:B ratio to 1:3, i.e. 25% A
* sublattice 2 with 1 site, atoms C,D, and no restriction

So basically it's a binary expansion, but I couldn't figure out a way to
tell the code that concentrations on sublattice 1 and 2 should not
interfere with each other. So I specified a quaternary expansion: 0/1 on
the first 4 sites, 2/3 on the 5th site. But still the concentration
restraint mixes the different atoms together. So the way I setup the
structure was likely not right? What's the best way to fix it?

Thanks!

**Comment by feifzhou** [comment]
Yes I was using the latest version. Like Wiley tested it exit quickly
without any output. Problem was that concentrations on different
sublattices and different atoms are mixed together.

**Comment by wsmorgan** [comment]
The structure is fine I think, if you update the concentration line to be:
```
20 20 100 # VARY CONSTRAINT
0 100 100
0 100 100
0 100 100
```
then what you should get for concentrations is always 1:3 for species A and B and either atom C or D on the second sublattice.

**Comment by feifzhou** [comment]
Thank you. This makes sense.

**Comment by glwhart** [comment]
If you have problems still, reopen this issue.

All the best, Fei!

**Comment by feifzhou** [comment]
Thank you that helped a lot
