### ISSUE TITLE
d-vector didn't permute in map_dvector_permutation

### ISSUE THREAD

**Issue by afonari** [msg-byu/enumlib#66]
```
$ enum.x input.in 
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n= 1 to  1
Including only structures of which the concentration of each atom is in the range:
Type: 1: 25/28--25/28
Type: 2: 3/28--3/28
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
 d-vector didn't permute in map_dvector_permutation
 This usually means that the d-set from the input structure and the d-set
 from the struct_enum.out have a different origin or don't live in the same
 unit cell. This probably isn't your fault---the code should overcome this.
 1 25 26 27  5  6  7  8 28 10 11 12 20 21 22 23 24  0  0 13 14 15 16 17  2  3  4  9
```
If I understand correctly,  two zeros are responsible for this error.

Is there a way to fix this?

Attached input: [input.txt](https://github.com/msg-byu/enumlib/files/1857163/input.txt)

**Comment by wsmorgan** [comment]
So this is a problem with floating point comparison tolerances that we've been working on. For now you can get it running again by using `0.01` as your tolerance instead of `0.001` in your input file. (I'm documenting the current behavior for future reference while we figure this out). The code is comparing 2 points and finding that they aren't equivalent:
atomic basis 18 
```
 rd   6.0970000000000004        2.3195000000000006        6.4595000000000002     
 d   6.0970000000000004        2.3185000000000002        6.4595000000000002     
```
atomic basis 19 
```
 rd   8.3510000000000009        2.3195000000000006        5.2474999999999996     
 d   8.3510000000000009        2.3185000000000002        5.2474999999999996     
```
As you can see these both differ in the second coordinate in the third decimal place.

@natefoulk4 Here is a test case for you!

**Comment by afonari** [comment]
Thanks @wsmorgan, that works!
