### ISSUE TITLE
Future project in labeling_related.

### ISSUE THREAD

**Issue by wsmorgan** [msg-byu/enumlib#7]
There are two comments in labeling_related.f90 that have no bearing on the functionality of the code, the subroutine (make_label_rotation_table) they are in isn't currently used, but that should be addressed later on so as to prevent anyone using the subroutine from having problems. They are on line 642 it says
`nR = 48 ! debug`
then on line 648 it says 
`allocate(tM(3,3,96),STAT=status) ! Why the 96? What's the appropriate number here? >48 but what?`

**Comment by glwhart** [comment]
I think this was changed by the Hamburg group because they wanted to use non-primitive cells---which can have more than 48 operations (because a lattice translation will then become a fractional translation). I don't like this approach---there's a proper way to handle this without this hack. But it happened when I wasn't watching...
